@card_services_HostAddress = http://localhost:5297
@key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJBZG1pbkBwcnVlYmEuY2wiLCJ1bmlxdWVfbmFtZSI6IkFkbWluIiwicm9sZSI6IkFkbWluIiwiQ2hhcmdlIjoiQWRtaW4iLCJuYmYiOjE3NzI1ODk2MjksImV4cCI6MTc3MjY3NjAyOSwiaWF0IjoxNzcyNTg5NjI5LCJpc3MiOiJjYXJkLXNlcnZpY2VzLWFwaSIsImF1ZCI6ImNhcmQtc2VydmljZXMtdXNlcnMifQ.PiTWU1EvQTFyzRvt9cTta9hzjkGgmVVmsvQFDq4rt4g
POST {{card_services_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "Email": "Admin@prueba.cl",
    "Password": "Admin123."
}

### createStudent
POST {{card_services_HostAddress}}/api/Student
Content-Type: application/json
Authorization: Bearer {{key}}

{
    "Name" :"PRUEBA",
    "Carrer":"PRUEBA",
    "Rut" :  "PRUEBA"
}
### StudentGET
GET  {{card_services_HostAddress}}/api/Student
Content-Type: application/json
Authorization: Bearer {{key}}

### StudentGETby id
GET  {{card_services_HostAddress}}/api/Student/1
Content-Type: application/json
Authorization: Bearer {{key}}

### update state
PATCH   {{card_services_HostAddress}}/api/Student/state/1
Content-Type: application/json
Authorization: Bearer {{key}}

### update User
PATCH   {{card_services_HostAddress}}/api/Student/update/1
Content-Type: application/json
Authorization: Bearer {{key}}

{
     "Carrer": "Prueba cambio", 
     "Name": "Prueba cambio" 
}

### Card get all
GET   {{card_services_HostAddress}}/api/Card/id=1
Content-Type: application/json
Authorization: Bearer {{key}}
###
GET {{card_services_HostAddress}}/api/card/12345678-9

###
GET {{card_services_HostAddress}}/api/card/verificate/12345678-




